#obraz bazowy .net
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
#tworzenie folderu
RUN mkdir app
#Wchodzimy do katalogu
WORKDIR /app
#aktualizacja
RUN apt-get update && \
    apt-get install -y git
#Klowanie repo
RUN git clone https://github.com/CodeMazeBlog/unit-testing-aspnetcore-webapi.git
#restor
RUN dotnet restore ./unit-testing-aspnetcore-webapi/netcore-unit-testing/web-api/web-api/web-api.csproj
#build
WORKDIR /app/unit-testing-aspnetcore-webapi/netcore-unit-testing/web-api/web-api
RUN dotnet build -c Release
#publish
FROM build as publish
WORKDIR /app/unit-testing-aspnetcore-webapi/netcore-unit-testing/web-api/web-api
RUN dotnet publish -c Release -o out
