version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - .:/ts-script
    image: node-app:latest

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - app
    image: node-test:alpine