# Użyj najnowszego obrazu Ubuntu jako punktu wyjścia
FROM ubuntu:latest

# Zaktualizuj repozytoria i zainstaluj Git
RUN apt-get update && \
    apt-get install -y git

# Ustaw domyślną komendę, która będzie uruchamiana podczas startu kontenera
CMD ["bash"]
