#!/bin/bash

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

# Wzorzec dla inicjałów i nr indexu
pattern="^MR404664"

if [[ ! $commit_msg =~ $pattern ]]; then
    echo "Błąd: Wiadomość commita musi zaczynać się od Twoich inicjałów (MR404664)."
    echo "Przykład poprawnej wiadomości: MR404664 - Treść commita"
    exit 1
fi

