- name: Zadanie do Sprawozdania
  hosts: Machines
  become: false
  tasks:
    - name: tworzenie katalogu
      file:
        path: ~/uploads
        state: directory
        mode: 0755

    - name: kopiowanie srodowiska
      copy:
        src: env
        dest: ~/uploads/env
        mode: 0755

    - name: make sure dnf-plugins.core installed
      dnf:
        name: dnf-plugins-core
        state: present
      become: yes
    - name: instalowanie repozytorium docker
      command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
      become: yes
    - name: sprawdzanie czy doker nie jest zainstalowawny
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        - docker
        - docker-common
        - container-selinux
        - docker-selinux
        - docker-engine
      become: yes
    - name: instalacja dockera
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - docker-ce
      become: yes
    - name: start dockera
      systemd:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: nginx
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
