FROM ubuntu:22.04


# Dependencies
RUN apt update -y
RUN apt install git -y
RUN apt install make -y
RUN apt install cmake -y
RUN apt install build-essential -y
RUN apt install zlib1g-dev -y
RUN apt install python3 -y

# Main repository
RUN git clone https://github.com/mattgodbolt/seasocks.git
WORKDIR seasocks

# General build
RUN mkdir build
WORKDIR build
RUN cmake .. -DUNITTESTS=1
RUN make -j$(nproc)
