- name: Configure SubServer
  hosts: machines
  become: yes

  tasks:
    - name: Create catalog ~/uploads, if not exist
      file:
        path: ~/uploads
        state: directory
        mode: 0755

    - name: create env file
      copy:
        src: "./env"
        dest: "~/uploads/env"
        mode: 0644

    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Run Docker Daemon
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Run nginx
      docker_container:
        name: nginx_container
        image: nginx
        state: started