---
- name: install docker on fedora
  hosts: devops-fedora
  become: true
  tasks:
    - name: install dnf-plugins-core
      command: dnf -y install dnf-plugins-core

    - name: install docker repository
      command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

    - name: install docker-engine
      command: dnf install --assumeyes docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
