---
- name: install docker on fedora
  hosts: devops-fedora
  become: true
  tasks:
    - name: install dnf-plugins-core
      dnf:
        name: dnf-plugins-core
        state: latest

    - name: install docker repository
      command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

    - name: install docker-ce
      dnf:
        name: docker-ce
        state: latest

    - name: install docker-ce-cli
      dnf:
        name: docker-ce-cli
        state: latest

    - name: install containerd.io
      dnf:
        name: containerd.io
        state: latest

    - name: install docker-buildx-plugin
      dnf:
        name: docker-buildx-plugin
        state: latest

    - name: docker-compose-plugin
      dnf:
        name: docker-compose-plugin
        state: latest
