FROM nginx:alpine

ARG buildtag

# Set the working directory for copying the static files
WORKDIR /usr/share/nginx/html

FROM build-29 as build

# Copy the static files from the build image specified by BUILD_TAG
COPY --from=build /coderpeak-palindrom/dist .

# Expose port 80 for Nginx
EXPOSE 80

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]
