version: "3.1"

networks:
  docker:

volumes:
  jenkins-data:

services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    networks:
      - docker
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://docker:2375 # Zmieniono port na 2375

  dind:
    image: docker:dind
    privileged: true
    restart: always
    networks:
      docker:
        aliases:
          - docker
    ports:
      - 2375:2375 # Zmieniono port na 2375
    environment:
      - DOCKER_TLS_CERTDIR= # Usunięto ścieżkę, aby wyłączyć TLS

  nginx:
    image: nginx:alpine
    restart: always
    networks:
      - docker
    ports:
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs:ro
