pipeline {
    agent any

    stages {
        stage('Clean') {
            steps {
                script {
                    deleteDir()

                    sh 'docker builder prune -a -f'
                }
            }
        }
        
        stage('Clone Repository') {
            steps {
                script {
                    git url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2024.git', branch: 'TB408752_Lab04'
                }
            }
        }
        
        stage('Build') {
            steps {
                script {
                    dir('GCL1/TB408752/Lab02') {
                        def dockerImage = "build_${env.JOB_NAME}_${env.BUILD_NUMBER}"
                        sh "docker build -t ${dockerImage} -f Dockerfile.build . --no-cache"
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    dir('GCL1/TB408752/Lab02') {
                        def dockerImage = "test_${env.JOB_NAME}_${env.BUILD_NUMBER}"
                        sh "docker build -t ${dockerImage} -f Dockerfile.test . --no-cache"
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    dir('GCL1/TB408752/Lab02') {
                        def dockerImage = "deploy_${env.JOB_NAME}_${env.BUILD_NUMBER}"
                        sh "docker build -t ${dockerImage} -f Dockerfile.deploy . --no-cache"

                        sh "docker run --name myapp -d -p 3000:80 ${dockerImage}"
                        sh 'docker ps'
                        sh 'sleep 10'
                        sh 'docker logs myapp'
                        sh 'docker stop myapp'
                        sh 'docker rm myapp'
                    }
                }
            }
        }

        stage('Publish') {
            steps {
                script {
                        def dockerHubUser = "toat"
                        def dockerHubToken = "TOKEN_GO_HERE"
                        def dockerHubRepo = "devops"
                        def dockerImage = "deploy_${env.JOB_NAME}_${env.BUILD_NUMBER}"
                        
                        sh "docker login -u ${dockerHubUser} -p ${dockerHubToken}"
                        sh "docker tag ${dockerImage}:latest ${dockerHubUser}/${dockerHubRepo}:${env.BUILD_NUMBER}"
                        sh "docker push ${dockerHubUser}/${dockerHubRepo}:${env.BUILD_NUMBER}"
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline successfully executed!'
        }
        failure {
            echo 'Pipeline failed! Check the logs for details.'
        }
    }
}
