pipeline {
    agent any

    environment {
        DOCKER_HOST = 'tcp://docker:2375' // Update with your Docker host address
    }

    stages {
        stage('Clone Repository') {
            steps {
                script {
                    git url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2024.git', branch: 'TB408752'
                }
            }
        }
        
        stage('Build') {
            steps {
                script {
                    dir('GCL1/TB408752/Lab2') {
                        def dockerImage = "build_${env.JOB_NAME}_${env.BUILD_NUMBER}"
                        docker.build(dockerImage, '-f Dockerfile.build .')
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline successfully executed!'
        }
        failure {
            echo 'Pipeline failed! Check the logs for details.'
        }
    }
}
