FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app

# Pobierz projekt
RUN apt-get update && \
    apt-get install -y git && \
    git clone https://github.com/davidfowl/TodoApi.git

# Build aplikacji testowej
WORKDIR /app/TodoApi/TodoApi
RUN dotnet build -c Release

# Wlaczenie testow
FROM build AS test
WORKDIR /app/TodoApi/TodoApi.Tests
RUN dotnet test