FROM node:20.10.0-alpine

COPY --from=docker-bldr /nest-simple/dist /dist
COPY --from=docker-bldr /nest-simple/node_modules /node_modules
COPY --from=docker-bldr /nest-simple/package.json /package.json

CMD ["npm", "run", "start:prod"]
