FROM node:20.10.0-alpine

COPY --from=nest-build /nest-simple/dist /app/dist
COPY --from=nest-build /nest-simple/node_modules /app/node_modules
COPY --from=nest-build /nest-simple/package.json /app/package.json

WORKDIR /app

CMD ["npm", "run", "start:prod"]
