pipeline {
    agent any

    stages {
        stage('Clear') {
            steps {
                echo 'Cleaning up'
                sh 'if [ -d MDO2024 ]; then rm -rf MDO2024; fi'
                sh 'docker system prune --all --force --volumes'
                sh 'if [ "$(docker ps -aq)" ]; then docker rm -f $(docker ps -aq); fi'
            }
        }

        stage('Clone CI repo') {
            steps {
                sh 'git clone https://github.com/InzynieriaOprogramowaniaAGH/MDO2024.git'
                dir('MDO2024') {
                    sh 'git checkout DW408167'
                }
            }
        }

        stage('Build') {
            steps {
                echo 'Running the build container'
                dir('MDO2024/GCL3/DW408167/Lab04') {
                    sh 'docker build -t nest-build . -f Dockerfile-build'
                }
            }
        }

        stage('Test') {
            steps {
                echo 'Running the test container'
                dir('MDO2024/GCL3/DW408167/Lab04') {
                    sh 'docker build -t nest-test . -f Dockerfile-test'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Running the deploy container'
                dir('MDO2024/GCL3/DW408167/Lab04') {
                    sh 'docker build -t nest-deploy . -f Dockerfile-deploy'

                    //// Run the deploy container
                    //sh 'docker run -p 3000:3000 -d --name nest-deploy-container nest-deploy'

                    //// Wait a bit for the container to start up
                    //sh 'sleep 5'

                    //// Execute the existing validation script
                    //sh './validation_script.sh'

                    //// Clean up: stop and remove the container
                    //sh 'docker stop nest-deploy-container'
                    //sh 'docker rm nest-deploy-container'
                }
            }
        }
        //stage('Publish') {
        //    steps {
        //        echo 'Publishing the image to the registry'
        //        dir('MDO2024/GCL3/DW408167/Lab04') {
        //            sh 'docker tag nest-deploy localhost:5000/nest-deploy:0.0.1'
        //            sh 'docker push localhost:5000/nest-deploy:0.0.1'
        //        }
        //    }
        //}
    }
}
